theme: minima
title: Yifei Chen
author: Yifei
email: yifei.chen@rug.nl
description: > # this means to ignore newlines until "baseurl:"
  This is my testing homepage.

# social links
twitter_username: TBA # DO NOT include the @ character, or else the build will fail!
github_username:  yifei-drl # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
